language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - phpenv config-add test/resources/php.ini

install:
  - composer install

script:
  - vendor/bin/phing travis

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: db9a4de41133c5c603bbd29c279541a5a3aa95c1b9e8d802bd8c118802a666bd
